project:
  type: book
  output-dir: _book
date: now
date-format: DD.MM.YYYY
author-title: Eier
book:
  title: 'Navs arbeidsarbeidsindikator og arbeidsmarkedet'
  description: Navs arbeidsindikator hvordan den er påvirket av arbeidsmarkedet. Fokus på bedriftsundersøkelsen.
    av tiltaksnedgang i Nav
  author: Jacob Sjødin
  chapters:
  - index.qmd
  - part: bedrift/intro.qmd
    chapters:
    - bedrift/rapport.qmd
  - part: jobb/intro.qmd
    chapters:
    - jobb/rapport.qmd
  - part: atid/intro.qmd
    chapters:
    - atid/rapport.qmd

  page-navigation: true
  page-footer: Nav - {{< meta date >}}
  repo-url: https://github.com/navikt/arbind-arbeidsmarked
  reader-mode: false
  search: true
  navbar:
    logo: assets/nav_logo_hvit.png
    logo-alt: Logo til Nav - Arbeids- og velferdsetaten
format:
  html:
    lang: nb
    toc: true
    toc-depth: 3
    theme:
      light: flatly
      dark: darkly
